# Generated by Django 6.0.4 on 2026-04-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='passed_quiz',
            field=models.BooleanField(default=False),
        ),
    ]
