# Generated by Django 6.0.4 on 2026-05-27 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_customuser_passed_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Název kategorie')),
                ('questions_per_quiz', models.PositiveIntegerField(default=1, verbose_name='Počet otázek v testu')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Pořadí')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_categories', to='courses.course', verbose_name='Kurz')),
            ],
            options={
                'verbose_name': 'Kategorie otázek',
                'verbose_name_plural': 'Kategorie otázek',
                'ordering': ['course', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='courses.questioncategory', verbose_name='Kategorie'),
        ),
    ]
