# Generated by Django 6.0.4 on 2026-06-11 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_questioncategory_question_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(choices=[('4', '§4 – osoba poučená'), ('6', '§6 – elektrotechnik'), ('7', '§7 – vedoucí elektrotechnik')], max_length=10)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending_payment', 'Čeká na platbu'), ('paid', 'Zaplaceno')], default='pending_payment', max_length=30)),
                ('ico', models.CharField(blank=True, max_length=20)),
                ('dic', models.CharField(blank=True, max_length=20)),
                ('company_name', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=120)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='courses.order')),
            ],
        ),
    ]
