# Generated by Django 6.0.4 on 2026-06-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_quizattempt_quizattemptquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncategory',
            name='slug',
            field=models.SlugField(default='obecne', max_length=100, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='questioncategory',
            unique_together={('course', 'slug')},
        ),
    ]
