# Generated by Django 6.0.4 on 2026-07-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_questioncategory_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
