# Generated by Django 6.0.4 on 2026-07-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_quizattempt_attempt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail kontaktní osoby'),
        ),
        migrations.AddField(
            model_name='order',
            name='contact_first_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Jméno kontaktní osoby'),
        ),
        migrations.AddField(
            model_name='order',
            name='contact_last_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Příjmení kontaktní osoby'),
        ),
        migrations.AddField(
            model_name='order',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Telefonní číslo'),
        ),
        migrations.AddField(
            model_name='order',
            name='contact_phone_prefix',
            field=models.CharField(default='+420', max_length=8, verbose_name='Telefonní předvolba'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=120, verbose_name='Město'),
        ),
        migrations.AlterField(
            model_name='order',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='Název firmy / jméno objednatele'),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(default='Česká republika', max_length=120, verbose_name='Země'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dic',
            field=models.CharField(blank=True, max_length=20, verbose_name='DIČ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ico',
            field=models.CharField(blank=True, max_length=20, verbose_name='IČO'),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='order',
            name='street',
            field=models.CharField(max_length=255, verbose_name='Ulice a číslo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='zip_code',
            field=models.CharField(max_length=20, verbose_name='PSČ'),
        ),
    ]
