# Generated by Django 6.0.4 on 2026-07-11 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_order_contact_email_order_contact_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderparticipant',
            name='activation_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aktivace dokončena'),
        ),
        migrations.AddField(
            model_name='orderparticipant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_participations', to=settings.AUTH_USER_MODEL, verbose_name='Uživatelský účet'),
        ),
        migrations.AlterField(
            model_name='orderparticipant',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='orderparticipant',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Jméno'),
        ),
        migrations.AlterField(
            model_name='orderparticipant',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Příjmení'),
        ),
        migrations.AlterField(
            model_name='orderparticipant',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='courses.order', verbose_name='Objednávka'),
        ),
        migrations.CreateModel(
            name='ParticipantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Evidenční číslo')),
                ('birth_date', models.DateField(verbose_name='Datum narození')),
                ('birth_place', models.CharField(max_length=150, verbose_name='Místo narození')),
                ('permanent_address', models.CharField(max_length=255, verbose_name='Trvalé bydliště')),
                ('employer_name', models.CharField(blank=True, max_length=255, verbose_name='Zaměstnavatel')),
                ('employer_address', models.CharField(blank=True, max_length=255, verbose_name='Adresa zaměstnavatele')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='courses.orderparticipant', verbose_name='Účastník')),
            ],
            options={
                'verbose_name': 'Profil účastníka',
                'verbose_name_plural': 'Profily účastníků',
                'ordering': ['-created_at'],
            },
        ),
    ]
