# Generated by Django 6.0.4 on 2026-07-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_orderparticipant_activation_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantprofile',
            name='registration_number',
        ),
        migrations.AddField(
            model_name='orderparticipant',
            name='registration_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Evidenční číslo'),
        ),
        migrations.CreateModel(
            name='RegistrationNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(choices=[('4', '§4 – osoba poučená'), ('6', '§6 – elektrotechnik'), ('7', '§7 – vedoucí elektrotechnik')], max_length=10, verbose_name='Typ kurzu')),
                ('year', models.PositiveIntegerField(verbose_name='Rok')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Měsíc')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='Poslední pořadové číslo')),
            ],
            options={
                'verbose_name': 'Řada evidenčních čísel',
                'verbose_name_plural': 'Řady evidenčních čísel',
                'constraints': [models.UniqueConstraint(fields=('course_type', 'year', 'month'), name='unique_registration_sequence_month')],
            },
        ),
    ]
