# Generated by Django 6.0.4 on 2026-07-11 17:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_participantprofile_registration_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderparticipant',
            name='activation_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datum odeslání aktivačního odkazu'),
        ),
        migrations.AddField(
            model_name='orderparticipant',
            name='activation_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, verbose_name='Aktivační token'),
        ),
        migrations.AlterField(
            model_name='orderparticipant',
            name='activation_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datum dokončení aktivace'),
        ),
    ]
