# Generated by Django 6.0.4 on 2026-07-11 17:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_orderparticipant_activation_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderparticipant',
            name='activation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Aktivační token'),
        ),
    ]
