# Generated by Django 6.0.4 on 2026-07-14 15:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_orderparticipant_activation_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=30, unique=True, verbose_name='Číslo osvědčení')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datum vystavení')),
                ('valid_until', models.DateField(verbose_name='Platnost do')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/%Y/%m/', verbose_name='PDF soubor')),
                ('verification_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Ověřovací token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificate', to='courses.orderparticipant', verbose_name='Účastník')),
                ('quiz_attempt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificate', to='courses.quizattempt', verbose_name='Úspěšný pokus testu')),
            ],
            options={
                'verbose_name': 'Osvědčení',
                'verbose_name_plural': 'Osvědčení',
                'ordering': ['-issued_at'],
            },
        ),
    ]
