# Generated by Django 6.0.4 on 2026-08-07 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='pdf_file',
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('participant_activation', 'Aktivace účastníka'), ('order_confirmation', 'Potvrzení objednávky'), ('course_completed', 'Dokončení kurzu')], max_length=50)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('preview', 'Náhled'), ('sent', 'Odesláno'), ('failed', 'Chyba')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='courses.order')),
                ('quiz_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='courses.quizattempt')),
            ],
        ),
    ]
