# Generated by Django 6.0.4 on 2026-08-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_remove_certificate_pdf_file_emaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(choices=[('participant_activation', 'Aktivace účastníka'), ('order_confirmation', 'Potvrzení objednávky'), ('course_completed', 'Dokončení kurzu'), ('payment_completed', 'Platba přijata')], max_length=50),
        ),
    ]
