# Generated by Django 6.0.4 on 2026-08-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_emaillog_email_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(choices=[('participant_activation', 'Aktivace účastníka'), ('course_completed', 'Dokončení kurzu'), ('payment_completed', 'Platba přijata')], max_length=50),
        ),
    ]
