# Generated by Django 6.0.4 on 2026-08-08 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_emaillog_email_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Odpověď', 'verbose_name_plural': 'Odpovědi'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Kurz', 'verbose_name_plural': 'Kurzy'},
        ),
        migrations.AlterModelOptions(
            name='emaillog',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'E-mailový záznam', 'verbose_name_plural': 'E-mailové záznamy'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Objednávka', 'verbose_name_plural': 'Objednávky'},
        ),
        migrations.AlterModelOptions(
            name='orderparticipant',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Účastník objednávky', 'verbose_name_plural': 'Účastníci objednávek'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Platba', 'verbose_name_plural': 'Platby'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['course', 'category', 'id'], 'verbose_name': 'Otázka', 'verbose_name_plural': 'Otázky'},
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-started_at'], 'verbose_name': 'Pokus testu', 'verbose_name_plural': 'Pokusy testů'},
        ),
        migrations.AlterModelOptions(
            name='quizattemptquestion',
            options={'ordering': ['order'], 'verbose_name': 'Otázka pokusu', 'verbose_name_plural': 'Otázky pokusů'},
        ),
    ]
